repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-merge-conflict
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
        # Rust attributes look like shebangs:)
        exclude: \.rs$
    -   id: check-symlinks
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: pretty-format-json
        args: [--autofix, --indent, '4']

-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
    -   id: cargo-check
    -   id: clippy

-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.14.0
    hooks:
    -   id: pretty-format-yaml
        args: [--autofix, --indent, '4']
    -   id: pretty-format-toml
        args: [--autofix, --indent, '4', --trailing-comma]
        exclude: ^Cargo.lock$

-   repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.32.1
    hooks:
    -   id: check-github-workflows

-   repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
    -   id: actionlint
        additional_dependencies:
        -   github.com/wasilibs/go-shellcheck/cmd/shellcheck@v0.10.0

-   repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.5.2
    hooks:
    -   id: zizmor
